### ISSUE TITLE
Colorizing breaks at rows >=20k chars

### ISSUE THREAD

**Issue by underdog** [mohsen1/vscode-prettify-json#10]
It appears that the prettifying stops working on rows with >= 20000 characters.   I've looked to see if there are any limitations to json itself, in regards to row char count, but can't find any.

**Comment by mohsen1** [comment]
I believe this is a native behavior of VSCode where syntax highlighting stops working in large files.

**Comment by underdog** [comment]
You are correct, https://github.com/Microsoft/vscode/issues/50056    changed it to 50k and the colorizing is still functioning.  Thanks for the quick reply :)
